{
 "title": "nwaku-monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Start Times (UTC)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"nwaku\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "waku_version{instance=\"nwaku:8003\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reachable (TODO)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "libp2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inbound/Outbound Connected Peers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "waku_connected_peers{direction=\"Outbound\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Rx/Tx Traffic (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "(increase(libp2p_network_bytes_total{direction=\"in\"}[15m]))/1000000/(900)*8",
     "legendFormat": "{{direction}}"
    },
    {
     "expr": "(increase(libp2p_network_bytes_total{direction=\"out\"}[15m]))/1000000/(900)*8",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "LibP2P Dials",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "libp2p_total_dial_attempts_total{}",
     "legendFormat": "{{__name__}}"
    },
    { "expr": "libp2p_failed_dials_total{}", "legendFormat": "{{__name__}}" },
    {
     "expr": "libp2p_successful_dials_total{}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Messages (1m rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "(increase(waku_node_messages_total[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Heap allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Nim Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "nim_gc_mem_bytes{}", "legendFormat": "{{__name__}}" },
    { "expr": "nim_gc_mem_occupied_bytes{}", "legendFormat": "{{__name__}}" },
    {
     "expr": "nim_gc_heap_instance_occupied_summed_bytes{}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}