# --discv5-discovery        Enable discovering nodes via Node Discovery v5
#                               [=false].
# --discv5-udp-port         Listening UDP port for Node Discovery v5.
#                               [=9000].
# --discv5-bootstrap-node   Text-encoded ENR for bootstrap node. Used when
#                               connecting to the network. Argument may be
#                               repeated..
# --discv5-enr-auto-update  Discovery can automatically update its ENR with
#                               the IP address and UDP port as seen by other
#                               nodes it communicates with. This option allows to
#                               enable/disable this functionality [=false].

discv5-discovery=true
#discv5-udp-port=
discv5-bootstrap-node=""
discv5-enr-auto-update=true
