# --dns-discovery              Enable DNS Discovery
# --dns-discovery-url          URL for DNS node list in format 'enrtree://<key>@<fqdn>'
# --dns-discovery-name-server  DNS name server IPs to query. Argument may be repeated.

dns-discovery=false
dns-discovery-url=
dns-discover-name-server=
