# --peer-exchange           Enable waku peer exchange protocol (responder
#                               side): true|false [=false].
# --peer-exchange-node      Peer multiaddr to send peer exchange requests to.
#                               (enables peer exchange protocol requester side).


peer-exchange=false
peer-exchange-node=
